In [3]:
def count_types(items):
    type_count = {}
    for item in items:
        type_name = type(item).__name__
        type_count[type_name] = type_count.get(type_name, 0) + 1
    return type_count

print(count_types([1, 2.5, "hello", True, 3, "world", 7]))


{'int': 3, 'float': 1, 'str': 2, 'bool': 1}


In [4]:
def convert_value(value, target_type):
    try:
        return target_type(value)
    except (ValueError, TypeError):
        return f"Error: Cannot convert {value!r} to {target_type.__name__}"

print(convert_value("123", int))
print(convert_value("abc", float))

123
Error: Cannot convert 'abc' to float


In [5]:
def validate_user(username, age, email):
    if not isinstance(username, str):
        return False
    try:
        age = int(age)
    except ValueError:
        return False
    if "@" not in email:
        return False
    return True

print(validate_user("Fadel", "25", "fadel@example.com"))
print(validate_user(123, "25", "no_at_symbol.com"))


True
False


In [7]:
def to_complex(num_str):
    try:
        return complex(num_str)
    except ValueError:
        return "Error: '{num_str}' is not a valid complex number"

print(to_complex("3+4j"))
print(to_complex("abc"))

(3+4j)
Error: '{num_str}' is not a valid complex number


In [8]:
import struct

def int_to_bytes_and_back(value, endian='little'):
    fmt = '<i' if endian == 'little' else '>i'
    packed = struct.pack(fmt, value)
    unpacked = struct.unpack(fmt, packed)[0]
    return packed, unpacked

print(int_to_bytes_and_back(12345, 'big'))

(b'\x00\x0009', 12345)


In [9]:
def is_even(n):
    return "Even" if (n & 1) == 0 else "Odd"

print(is_even(4))
print(is_even(7))

Even
Odd


In [11]:
def find_line_with_keyword(filename, keyword):
    with open(filename, 'r') as f:
        while (line := f.readline()):
            if keyword in line:
                return line.strip()
    return None


In [12]:
def compare_is_and_equals():
    a = [1, 2, 3]
    b = [1, 2, 3]
    x = 5
    y = 5
    return (a is b, a == b, x is y, x == y)

print(compare_is_and_equals())

(False, True, True, True)


In [13]:
def compound_interest(principal, rate, time):
    amount = principal
    for _ in range(time):
        amount += amount * rate
    return amount

print(compound_interest(1000, 0.05, 3))


1157.625


In [15]:
def extract_bits(num, start, end):
    mask = ((1 << (end - start + 1)) - 1) << start
    return (num & mask) >> start

print(extract_bits(0b111100110101, 5, 10))


57


In [16]:
for i in range(1, 101):
    if i % 3 == 0 and i % 5 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [17]:
def prime_factors(n):
    factors = []
    i = 2
    while i * i <= n:
        if n % i == 0:
            factors.append(i)
            n //= i
        else:
            i += 1
    if n > 1:
        factors.append(n)
    return factors

print(prime_factors(84))


[2, 2, 3, 7]


In [18]:
def binary_search(arr, target):
    low, high = 0, len(arr) - 1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1

print(binary_search([1, 3, 5, 7, 9, 11], 7))


3


In [20]:
def adventure_game():
    print("You are in a forest. Do you go left or right?")
    choice = input("Choice: ").lower()
    if choice == "left":
        print("You find a river. Do you swim or build a raft?")
        action = input("Action: ").lower()
        if action == "swim":
            print("You were eaten by a crocodile.")
        else:
            print("You safely crossed the river.")
    elif choice == "right":
        print("You meet a stranger. Talk or run?")
        action = input("Action: ").lower()
        if action == "talk":
            print("The stranger gives you gold.")
        else:
            print("You got lost in the woods.")
    else:
        print("Invalid choice.")

adventure_game()


You are in a forest. Do you go left or right?


Choice:  left


You find a river. Do you swim or build a raft?


Action:  swim


You were eaten by a crocodile.


In [21]:
import timeit

def fibonacci_loop(n):
    seq = [0, 1]
    for i in range(2, n):
        seq.append(seq[-1] + seq[-2])
    return seq[n-1]

def fibonacci_recursion(n):
    if n <= 1:
        return n
    return fibonacci_recursion(n-1) + fibonacci_recursion(n-2)

print(timeit.timeit("fibonacci_loop(35)", globals=globals(), number=1))
print(timeit.timeit("fibonacci_recursion(35)", globals=globals(), number=1))


6.799993570894003e-06
1.9846735000028275


In [22]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

print(bubble_sort([64, 34, 25, 12, 22, 11, 90]))


[11, 12, 22, 25, 34, 64, 90]


In [23]:
nums = [121, 123, 44, 78987, 1001, 345]
palindromes = list(filter(lambda x: str(x) == str(x)[::-1], nums))
print(palindromes)


[121, 44, 78987, 1001]


In [24]:
a, b, c = 1, 2, 1
nums = [1, 2, 3, 4, 5]
quadratic = list(map(lambda x: a*x**2 + b*x + c, nums))
print(quadratic)


[4, 9, 16, 25, 36]


In [25]:
from functools import lru_cache

@lru_cache(None)
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

print(factorial(10))


3628800


In [26]:
def tower_of_hanoi(n, source, auxiliary, target):
    if n == 1:
        print(f"Move disk 1 from {source} to {target}")
        return
    tower_of_hanoi(n-1, source, target, auxiliary)
    print(f"Move disk {n} from {source} to {target}")
    tower_of_hanoi(n-1, auxiliary, source, target)

tower_of_hanoi(3, 'A', 'B', 'C')


Move disk 1 from A to C
Move disk 2 from A to B
Move disk 1 from C to B
Move disk 3 from A to C
Move disk 1 from B to A
Move disk 2 from B to C
Move disk 1 from A to C


In [27]:
def bad_scope():
    x = 10
bad_scope()
# print(x)  # Erreur : variable locale inaccessible

def good_scope():
    x = 10
    return x
y = good_scope()
print(y)


10


In [28]:
import time

def timer(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print("Execution time:", end - start)
        return result
    return wrapper

@timer
def slow_function():
    for _ in range(10**6):
        pass

slow_function()


Execution time: 0.015513181686401367


In [29]:
lists = [[1, 2], [3, 4]]
flattened = [x for sublist in lists for x in sublist]
print(flattened)


[1, 2, 3, 4]


In [30]:
def flatten_recursive(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten_recursive(item))
        else:
            result.append(item)
    return result

print(flatten_recursive([1, [2, [3, 4], 5], [6, 7]]))


[1, 2, 3, 4, 5, 6, 7]


In [31]:
def most_frequent_word(text):
    words = text.split()
    freq = {}
    for w in words:
        freq[w] = freq.get(w, 0) + 1
    return max(freq, key=freq.get)

print(most_frequent_word("apple banana apple orange banana apple"))


apple


In [32]:
def lists_to_dict(keys, values):
    length = min(len(keys), len(values))
    return {keys[i]: values[i] for i in range(length)}

print(lists_to_dict(['a', 'b', 'c'], [1, 2]))


{'a': 1, 'b': 2}


In [33]:
def remove_duplicates(lst):
    seen = set()
    result = []
    for item in lst:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

print(remove_duplicates([1, 2, 2, 3, 4, 1, 5]))


[1, 2, 3, 4, 5]


In [34]:
from collections import OrderedDict

class LRUCache:
    def __init__(self, capacity):
        self.cache = OrderedDict()
        self.capacity = capacity

    def get(self, key):
        if key in self.cache:
            self.cache.move_to_end(key)
            return self.cache[key]
        return -1

    def put(self, key, value):
        if key in self.cache:
            self.cache.move_to_end(key)
        self.cache[key] = value
        if len(self.cache) > self.capacity:
            self.cache.popitem(last=False)

cache = LRUCache(2)
cache.put(1, 'A')
cache.put(2, 'B')
cache.get(1)
cache.put(3, 'C')
print(list(cache.cache.items()))


[(1, 'A'), (3, 'C')]


In [35]:
def invert_dict(d):
    inverted = {}
    for k, v in d.items():
        inverted.setdefault(v, []).append(k)
    return inverted

print(invert_dict({'a': 1, 'b': 2, 'c': 1}))


{1: ['a', 'c'], 2: ['b']}


In [36]:
class BankAccount:
    def __init__(self, balance=0):
        self.__balance = balance

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount

    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount

    def get_balance(self):
        return self.__balance

account = BankAccount(100)
account.deposit(50)
account.withdraw(30)
print(account.get_balance())


120


In [37]:
import math

class Vector:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __add__(self, other):
        return Vector(self.x + other.x, self.y + other.y)

    def __sub__(self, other):
        return Vector(self.x - other.x, self.y - other.y)

    def magnitude(self):
        return math.sqrt(self.x**2 + self.y**2)

    def __str__(self):
        return f"({self.x}, {self.y})"

v1 = Vector(3, 4)
v2 = Vector(1, 2)
print(v1 + v2)
print(v1 - v2)
print(v1.magnitude())


(4, 6)
(2, 2)
5.0


In [38]:
class Book:
    def __init__(self, title, author, isbn):
        self.title = title
        self.author = author
        self.isbn = isbn

    def __repr__(self):
        return f"Book(title={self.title!r}, author={self.author!r}, isbn={self.isbn!r})"

book = Book("1984", "George Orwell", "1234567890")
print(book)


Book(title='1984', author='George Orwell', isbn='1234567890')


In [39]:
class Vehicle:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

    def info(self):
        return f"{self.brand} {self.model}"

class Car(Vehicle):
    def __init__(self, brand, model, doors):
        super().__init__(brand, model)
        self.doors = doors

    def info(self):
        return f"{self.brand} {self.model} with {self.doors} doors"

class Bicycle(Vehicle):
    def __init__(self, brand, model, gear_count):
        super().__init__(brand, model)
        self.gear_count = gear_count

    def info(self):
        return f"{self.brand} {self.model} with {self.gear_count} gears"

class Truck(Vehicle):
    def __init__(self, brand, model, capacity):
        super().__init__(brand, model)
        self.capacity = capacity

    def info(self):
        return f"{self.brand} {self.model} with capacity {self.capacity} tons"

car = Car("Toyota", "Corolla", 4)
bike = Bicycle("Trek", "FX 3", 21)
truck = Truck("Volvo", "FH", 18)
print(car.info())
print(bike.info())
print(truck.info())


Toyota Corolla with 4 doors
Trek FX 3 with 21 gears
Volvo FH with capacity 18 tons


In [40]:
from abc import ABC, abstractmethod
import math

class Shape(ABC):
    @abstractmethod
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius ** 2

class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height

class Triangle(Shape):
    def __init__(self, base, height):
        self.base = base
        self.height = height

    def area(self):
        return 0.5 * self.base * self.height

print(Circle(5).area())
print(Rectangle(4, 6).area())
print(Triangle(3, 8).area())


78.53981633974483
24
12.0


In [41]:
class SmartDevice:
    def connect_wifi(self):
        return "Connected to WiFi"

class Phone:
    def make_call(self, number):
        return f"Calling {number}"

class SmartPhone(SmartDevice, Phone):
    def take_photo(self):
        return "Photo taken"

phone = SmartPhone()
print(phone.connect_wifi())
print(phone.make_call("123456789"))
print(phone.take_photo())
print(SmartPhone.__mro__)


Connected to WiFi
Calling 123456789
Photo taken
(<class '__main__.SmartPhone'>, <class '__main__.SmartDevice'>, <class '__main__.Phone'>, <class 'object'>)


In [42]:
class Shape:
    def draw(self):
        pass

class Circle(Shape):
    def draw(self):
        print("Drawing a Circle")

class Rectangle(Shape):
    def draw(self):
        print("Drawing a Rectangle")

class Triangle(Shape):
    def draw(self):
        print("Drawing a Triangle")

shapes = [Circle(), Rectangle(), Triangle()]
for s in shapes:
    s.draw()


Drawing a Circle
Drawing a Rectangle
Drawing a Triangle


In [43]:
class BankAccount:
    def __init__(self, balance=0):
        self.__balance = balance

    @property
    def balance(self):
        return self.__balance

    @balance.setter
    def balance(self, value):
        if value >= 0:
            self.__balance = value

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount

    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount

account = BankAccount(100)
account.deposit(50)
account.withdraw(30)
print(account.balance)
account.balance = 500
print(account.balance)


120
500


In [44]:
class Printable:
    def print_info(self):
        print(self.__dict__)

class Vehicle(Printable):
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

class Book(Printable):
    def __init__(self, title, author, isbn):
        self.title = title
        self.author = author
        self.isbn = isbn

v = Vehicle("Toyota", "Corolla")
b = Book("1984", "George Orwell", "1234567890")
v.print_info()
b.print_info()


{'brand': 'Toyota', 'model': 'Corolla'}
{'title': '1984', 'author': 'George Orwell', 'isbn': '1234567890'}


In [50]:
%%writefile mymath.py
import math
def add(a, b): return a + b
def multiply(a, b): return a * b
def sqrt(x): return math.sqrt(x)

Writing mymath.py


In [51]:
import mymath

print(mymath.add(5, 3))
print(mymath.multiply(4, 2))
print(mymath.sqrt(16))

8
8
4.0


In [62]:
!mkdir -p mypackage


Un sous-r‚pertoire ou un fichier -p existe d‚j….
Une erreur s'est produite lors du traitement deÿ: -p.
Un sous-r‚pertoire ou un fichier mypackage existe d‚j….
Une erreur s'est produite lors du traitement deÿ: mypackage.


In [63]:
%%writefile mypackage/__init__.py


UsageError: %%writefile is a cell magic, but the cell body is empty.


In [64]:
%%writefile mypackage/module1.py
def greet(name):
    return f"Hello, {name}!"


Overwriting mypackage/module1.py


In [65]:
%%writefile mypackage/module2.py
from .module1 import greet

def welcome(name):
    return greet(name) + " Welcome to the package."


Overwriting mypackage/module2.py


In [66]:
from mypackage.module2 import welcome
print(welcome("Fadel"))


Hello, Fadel! Welcome to the package.


In [67]:
import sys

sys.argv = ["notebook", "arg1", "arg2", "arg3"]

if len(sys.argv) > 1:
    print("Arguments reçus :", sys.argv[1:])
else:
    print("Aucun argument fourni.")

Arguments reçus : ['arg1', 'arg2', 'arg3']


In [68]:
%%writefile module_test.py
def main():
    print("Ce module est exécuté directement.")

if __name__ == "__main__":
    main()

Writing module_test.py


In [69]:
import module_test


In [70]:
!python module_test.py


Ce module est exécuté directement.


In [72]:
def get_integer():
    while True:
        try:
            n = int(input("Enter an integer: "))
            return n
        except ValueError:
            print("Invalid input, try again.")

get_integer()  


Enter an integer:  1


1

In [77]:
import os

class ChangeDir:
    def __init__(self, path):
        self.path = path
        self.original = os.getcwd()
    def __enter__(self):
        os.chdir(self.path)
    def __exit__(self, exc_type, exc_val, exc_tb):
        os.chdir(self.original)

# Exemple d'utilisation :
# with ChangeDir("/tmp"):
#     print(os.getcwd())
# print(os.getcwd())


In [78]:
class InvalidEmailError(Exception):
    pass

def validate_user(username, age, email):
    if not isinstance(username, str):
        return False
    try:
        age = int(age)
    except ValueError:
        return False
    if "@" not in email:
        raise InvalidEmailError("Invalid email format.")
    return True

try:
    print(validate_user("Fadel", 25, "fadelgmail.com"))
except InvalidEmailError as e:
    print(e)


Invalid email format.


In [79]:
import csv

with open("data.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["name", "score"])
    writer.writerow(["Alice", 80])
    writer.writerow(["Bob", 90])
    writer.writerow(["Charlie", 70])

def average_column(filename, column):
    with open(filename, newline="") as f:
        reader = csv.DictReader(f)
        values = [float(row[column]) for row in reader]
    return sum(values) / len(values)

print(average_column("data.csv", "score"))


80.0


In [80]:
def copy_file(src, dest):
    with open(src, "r") as f1, open(dest, "w") as f2:
        f2.write(f1.read())

copy_file("data.csv", "data_copy.csv")


In [81]:
with open("log.txt", "w") as f:
    f.write("INFO: system started\n")
    f.write("ERROR: disk not found\n")
    f.write("INFO: retrying\n")
    f.write("ERROR: connection lost\n")

def error_lines(filename):
    with open(filename, "r") as f:
        for line in f:
            if "ERROR" in line:
                yield line

with open("errors.txt", "w") as out:
    for line in error_lines("log.txt"):
        out.write(line)

with open("errors.txt") as f:
    print(f.read())


ERROR: disk not found
ERROR: connection lost



In [82]:
import json

data = {"name": "Fadel", "age": 25}
with open("user.json", "w") as f:
    json.dump(data, f)

with open("user.json", "r") as f:
    user = json.load(f)

user["age"] = 26

with open("user.json", "w") as f:
    json.dump(user, f)

with open("user.json") as f:
    print(f.read())


{"name": "Fadel", "age": 26}


In [83]:
import re

def validate_email(email):
    pattern = r"^[\w\.-]+@[\w\.-]+\.\w+$"
    return bool(re.match(pattern, email))

print(validate_email("fadel@example.com"))
print(validate_email("invalid@com"))


True
False


In [84]:
text = "Today's date is 2025-10-06. The project started on 2023-09-15 and ended on 2024-12-01."
dates = re.findall(r"\b\d{4}-\d{2}-\d{2}\b", text)
print(dates)


['2025-10-06', '2023-09-15', '2024-12-01']


In [85]:
text = "This is a bad example of a bad word."
censored = re.sub(r"\bbad\b", "***", text, flags=re.IGNORECASE)
print(censored)


This is a *** example of a *** word.


In [86]:
log = "ERROR 2023-10-27 14:32:10: Connection failed"
pattern = r"(?P<level>[A-Z]+)\s(?P<date>\d{4}-\d{2}-\d{2})\s(?P<time>\d{2}:\d{2}:\d{2}):\s(?P<message>.+)"
match = re.match(pattern, log)
if match:
    print(match.groupdict())


{'level': 'ERROR', 'date': '2023-10-27', 'time': '14:32:10', 'message': 'Connection failed'}


In [87]:
import sqlite3

conn = sqlite3.connect("users.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    email TEXT
)
""")
conn.commit()
conn.close()


In [88]:
def insert_user(name, email):
    conn = sqlite3.connect("users.db")
    cursor = conn.cursor()
    cursor.execute("INSERT INTO users (name, email) VALUES (?, ?)", (name, email))
    conn.commit()
    conn.close()

insert_user("Fadel", "fadel@example.com")
insert_user("Amina", "amina@example.com")


In [89]:
def get_all_users():
    conn = sqlite3.connect("users.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM users")
    rows = cursor.fetchall()
    conn.close()
    return rows

print(get_all_users())


[(1, 'Fadel', 'fadel@example.com'), (2, 'Amina', 'amina@example.com')]


In [90]:
def update_email(user_id, new_email):
    conn = sqlite3.connect("users.db")
    cursor = conn.cursor()
    cursor.execute("UPDATE users SET email = ? WHERE id = ?", (new_email, user_id))
    conn.commit()
    conn.close()

update_email(1, "newfadel@example.com")
print(get_all_users())


[(1, 'Fadel', 'newfadel@example.com'), (2, 'Amina', 'amina@example.com')]


In [91]:
class UserDAO:
    def __init__(self, db_name="users.db"):
        self.db_name = db_name

    def create_user(self, name, email):
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        cursor.execute("INSERT INTO users (name, email) VALUES (?, ?)", (name, email))
        conn.commit()
        conn.close()

    def get_users(self):
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM users")
        rows = cursor.fetchall()
        conn.close()
        return rows

    def update_user(self, user_id, email):
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        cursor.execute("UPDATE users SET email = ? WHERE id = ?", (email, user_id))
        conn.commit()
        conn.close()

    def delete_user(self, user_id):
        conn = sqlite3.connect(self.db_name)
        cursor = conn.cursor()
        cursor.execute("DELETE FROM users WHERE id = ?", (user_id,))
        conn.commit()
        conn.close()

dao = UserDAO()
dao.create_user("Karim", "karim@example.com")
print(dao.get_users())
dao.update_user(2, "amina.new@example.com")
print(dao.get_users())
dao.delete_user(3)
print(dao.get_users())


[(1, 'Fadel', 'newfadel@example.com'), (2, 'Amina', 'amina@example.com'), (3, 'Karim', 'karim@example.com')]
[(1, 'Fadel', 'newfadel@example.com'), (2, 'Amina', 'amina.new@example.com'), (3, 'Karim', 'karim@example.com')]
[(1, 'Fadel', 'newfadel@example.com'), (2, 'Amina', 'amina.new@example.com')]


In [1]:
import numpy as np

arr = np.random.randint(1, 101, (10, 10))
arr[arr % 2 == 0] = -arr[arr % 2 == 0]
print(arr)


[[ 49  17 -58  59 -92  53 -72  -8 -76  95]
 [ 55  69  43  23 -38  27 -38 -40  21   3]
 [ 35 -78 -88  -6 -30 -12 -26   7 -28 -18]
 [-22  37  91  73  -4  39  39  53 -36  11]
 [-92 -86  91 -80 -98 -96  13 -28  25 -66]
 [-82 -88  61  91  27 -42 -78 -44  11  83]
 [-16   1  57  51 -86 -72  67  59 -38 -40]
 [ 71  -2 -12 -54 -60  95 -82 -44 -20  65]
 [ 33  63 -72  19  25  47  41  55 -22 -58]
 [ 19 -52 -88 -74  79  63  65 -20 -12  15]]


In [2]:
temps = np.random.uniform(32, 212, 100)
hot = temps[temps > 80]
print(hot)


[118.59611568 200.67214526 195.37345817  87.3863442  109.03732605
 163.78629289 110.99916972 141.11496902 177.52705379 121.757987
 176.31146596 153.50814495 145.76196222 146.44517057  86.34767976
 133.70551797 117.7257341  185.42504485  80.29876416 133.16861816
 149.05005267 156.76360448 207.0485874  140.05512192 180.67877669
 199.01790134 113.83659698 196.90897581 190.70110204 119.25668724
 184.69607106 124.61134588 116.93278481 188.21748131 157.57698464
 117.49013478  88.64462363 180.02892499 125.04345054 146.17670596
  96.90055238 191.80970869  96.52546515 136.46621385 149.88378133
 123.58736734 149.19159867 175.22602491 179.47103183 149.47755886
 203.81737448 119.25457829 186.81276268 162.73303703 177.04270874
 179.31351302 170.97464403 181.00396846 147.97758225 173.90274545
 145.90471293 153.54143675 156.99013926 198.06572665 166.77335033
 140.32088723 187.39518662 197.83584338 101.8138411  133.23581916
 150.45105011  82.17822995 176.14842935 117.95558687 152.37053582
 107.7812435

In [3]:
a = np.random.rand(5, 5)
b = np.random.rand(5, 5)
distance = np.sqrt((a - b) ** 2)
print(distance)


[[0.42426891 0.59870951 0.94216634 0.3361148  0.31546877]
 [0.22804267 0.2739573  0.27571499 0.41191054 0.72261885]
 [0.20468823 0.52684942 0.17782216 0.05094373 0.35908189]
 [0.48320142 0.10863181 0.13699749 0.03905969 0.40260537]
 [0.74516388 0.55703316 0.4895627  0.13054897 0.8707385 ]]


In [4]:
v = np.random.rand(5)
M = np.random.rand(10, 5)
result = M - v
print(result)


[[ 0.01845054 -0.43060333  0.43003129 -0.58350059  0.15785749]
 [-0.34036083  0.01046507  0.2141914  -0.44313227  0.21091075]
 [-0.51104446  0.28052965  0.79669604  0.15611757 -0.10230055]
 [-0.60738026 -0.40315568  0.52356483 -0.10591565  0.22969832]
 [-0.19956252  0.16454795  0.5258789  -0.45793838  0.69370042]
 [-0.686907   -0.34114562  0.17951755  0.15099318  0.60687358]
 [-0.04733726  0.24000379  0.2255951  -0.30276228  0.18710548]
 [-0.08381496 -0.20809995  0.51850763 -0.33216119  0.13269424]
 [ 0.15832108  0.55048354  0.04614743  0.28413177  0.49111922]
 [-0.66988623  0.04921364  0.547066   -0.24217911  0.76063497]]


In [5]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print(x)
print(np.allclose(np.dot(A, x), b))


[2. 3.]
True


In [6]:
import pandas as pd
import numpy as np

data = {"date": pd.date_range(start="2025-01-01", periods=30, freq="D"),
        "daily_sales": np.random.randint(50, 500, 30)}
df = pd.DataFrame(data)
df["rolling_avg"] = df["daily_sales"].rolling(window=7).mean()
print(df.head(10))


        date  daily_sales  rolling_avg
0 2025-01-01          224          NaN
1 2025-01-02          183          NaN
2 2025-01-03          420          NaN
3 2025-01-04          118          NaN
4 2025-01-05           68          NaN
5 2025-01-06          376          NaN
6 2025-01-07          475   266.285714
7 2025-01-08          356   285.142857
8 2025-01-09           72   269.285714
9 2025-01-10          303   252.571429


In [7]:
df = pd.DataFrame({
    "Dept": ["HR", "IT", "HR", "IT", "Sales"],
    "Age": [25, np.nan, 30, np.nan, 40],
    "Salary": [4000, 5000, np.nan, 6000, np.nan]
})

df["Age"].fillna(df["Age"].median(), inplace=True)
df["Salary"] = df.groupby("Dept")["Salary"].transform(lambda x: x.fillna(x.mean()))
print(df)


    Dept   Age  Salary
0     HR  25.0  4000.0
1     IT  30.0  5000.0
2     HR  30.0  4000.0
3     IT  30.0  6000.0
4  Sales  40.0     NaN


C:\Users\fofab\AppData\Local\Temp\ipykernel_81416\1940107434.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)


In [8]:
sales = pd.DataFrame({
    "Year": [2023, 2023, 2024, 2024, 2024],
    "Product_Category": ["A", "B", "A", "B", "A"],
    "Sales": [1000, 1500, 1200, 1300, 1100],
    "Profit_Margin": [0.1, 0.15, 0.12, 0.14, 0.09]
})

result = sales.groupby(["Year", "Product_Category"]).agg(
    Total_Sales=("Sales", "sum"),
    Avg_Profit_Margin=("Profit_Margin", "mean")
)
print(result)


                       Total_Sales  Avg_Profit_Margin
Year Product_Category                                
2023 A                        1000              0.100
     B                        1500              0.150
2024 A                        2300              0.105
     B                        1300              0.140


In [9]:
df = pd.DataFrame({
    "city_name": ["New York", "Los Angeles", "Paris", "New Delhi", "Lagos"],
    "population": [8500000, 4000000, 2200000, 31000000, 15000000],
    "area": [468, 503, 105, 1484, 1171]
})

filtered = df.query("(population > 1000000 and area < 500) or city_name.str.contains('New')")
print(filtered)


   city_name  population  area
0   New York     8500000   468
2      Paris     2200000   105
3  New Delhi    31000000  1484


In [10]:
orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4],
    "customer_id": [101, 102, 103, 104],
    "product_id": [1, 2, 5, 3]
})

products = pd.DataFrame({
    "product_id": [1, 2, 3],
    "product_name": ["Laptop", "Phone", "Tablet"],
    "price": [1000, 500, 300]
})

merged = pd.merge(orders, products, on="product_id", how="left")
print(merged)


   order_id  customer_id  product_id product_name   price
0         1          101           1       Laptop  1000.0
1         2          102           2        Phone   500.0
2         3          103           5          NaN     NaN
3         4          104           3       Tablet   300.0


In [11]:
import pandas as pd
import numpy as np

dates = pd.date_range("2025-01-01", periods=60, freq="D")
sales_data = pd.DataFrame({
    "Date": dates,
    "Salesperson": np.random.choice(["Alice", "Bob", "Charlie"], size=60),
    "Revenue": np.random.randint(100, 1000, size=60)
})

sales_data["Month"] = sales_data["Date"].dt.to_period("M")
pivot = pd.pivot_table(sales_data, values="Revenue", index="Month", columns="Salesperson", aggfunc="sum", fill_value=0)
print(pivot)


Salesperson  Alice   Bob  Charlie
Month                            
2025-01       4515  6797     5437
2025-02       5322  3024     6157
2025-03        638     0        0


In [12]:
dates = pd.date_range("2025-01-01", periods=90, freq="D")
df = pd.DataFrame({
    "Date": dates,
    "volume": np.random.randint(100, 1000, 90),
    "closing_price": np.random.uniform(50, 150, 90)
})
df.set_index("Date", inplace=True)

resampled = df.resample("W").agg({"volume": "sum", "closing_price": "last"})
print(resampled.head())


            volume  closing_price
Date                             
2025-01-05    4077      65.099838
2025-01-12    3421      70.995267
2025-01-19    4314     133.721929
2025-01-26    5381     114.776078
2025-02-02    3457      74.623486


In [13]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

data = fetch_california_housing(as_frame=True)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", Ridge(random_state=42))
])

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))


MSE: 0.5558548589435969
R2: 0.5758157428913686


In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
import numpy as np

models = {
    "LinearRegression": LinearRegression(),
    "RandomForest": RandomForestRegressor(random_state=42, n_jobs=-1),
    "SVR": SVR()
}

for name, model in models.items():
    pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("model", model)
    ])
    scores = cross_val_score(pipe, X, y, cv=5, scoring="r2", n_jobs=-1)
    print(name, "mean R2:", np.mean(scores), "std R2:", np.std(scores))


LinearRegression mean R2: 0.5530311140279567 std R2: 0.061691601409532754
RandomForest mean R2: 0.6559022792657999 std R2: 0.07847065187260781
SVR mean R2: 0.66869593304241 std R2: 0.056406686373962234


In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

iris = load_iris(as_frame=True)
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

